#!/bin/bash

# absolute path to the SCION binary
binary=$1
# config_file has form of /var/lib/scion/ISD-isd-/AS-as-/endhost/sd.toml
# with variables to substitute marked with dashes
config_file=$2
# v has form of 16-ffaa_0_1002 or 16-ffaa_0_1002-1
v=$3

isd=${v%%-*_*}
suffix=${v#*-}
as=${suffix%-*}

# we use ampersand in sed below as slash is present in the input string
# therefore cannot be used as sed separator
config_file=$(echo ${config_file} | sed 's@-isd-@'"${isd}"'@')
#config_file=$(echo ${config_file} | sed 's@-suffix-@'"${suffix}"'@')
config_file=$(echo ${config_file} | sed 's@-as-@'"${as}"'@')

exec ${binary} -config ${config_file}
