#!/usr/bin/env bash
set -e

# Create system user and group for scion
id sciond || adduser --system --no-create-home sciond
getent group sciond || groupadd sciond && usermod -g sciond sciond

# Create directory for logs and own it
mkdir -p /var/log/scion/
chown sciond:sciond /var/log/scion/

# Same for gen folder
mkdir -p /etc/scion/
chown -R sciond:sciond /etc/scion/

# Reload systemd unit files after installing a new one
systemctl daemon-reload
